package com.leaprnd.deltadom.json;

enum JSONEventType {
	DELETE_NODE,
	DELETE_ELEMENT,
	INSERT_COMMENT,
	INSERT_ELEMENT,
	INSERT_TEXT,
	MOVE_NODE,
	MOVE_ELEMENT,
	REMOVE_ATTRIBUTE,
	SET_ATTRIBUTE,
	SET_VALUE
}
